### PR TITLE
Adding MalUnpack Pyhon Library 

### PR DESCRIPTION
**Pull request by fr0gger**
Hi, I created a python library wrapper for importing MalUnpack, this is similar to the runner, but the lib can be used for automation and other applications. It also retrieves the JSON results from Mal_Unpack.exe. :)

### CODE REVIEW

**Comment by hasherezade** [comment]
Nice, thank you!

**Comment by hasherezade** [comment]
The only remark that I have is that I will not like to keep `mal_unpack.exe` in the repository. Also keeping duplicated `dll_load` is too much. Maybe we can replace them with some script that will prepare the stage by downloading them and putting to the proper directory.

**Comment by hasherezade** [comment]
@fr0gger - I reworked it a bit, check it out: https://github.com/hasherezade/mal_unpack/tree/master/mal_unpack_lib

**Comment by fr0gger** [comment]
Excellent! Yeah this is a better option @hasherezade :)

**Comment by hasherezade** [comment]
@fr0gger FYI - I moved the Python wrappers into a separate repo: https://github.com/hasherezade/mal_unpack_py - because they are separate modules, not anyhow related with its cpp code, but just making use of the `mal_unpack.exe` .

Also, separating it will come more handy for people who just want to use Python wrappers (rather than compile mal_unpack from the source) - they will not have to download the part of code that is irrelevant for them.

**Pull request merged**
